version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: axe-core
    versions:
    - 4.1.1
    - 4.1.2
    - 4.1.3
    - 4.1.4
  - dependency-name: eslint-config-brightspace
    versions:
    - 0.11.0
    - 0.12.0
    - 0.13.0
    - 0.13.1
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
