name: CI
on: pull_request
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Unit Tests (SauceLabs)
        run: npm run test:sauce
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY_HORGAN }}
          SAUCE_USERNAME: Horgan
      - name: Lint (CSS)
        run: npm run lint:style
